{% set version = "0.3.9" %}

package:
  name: etuples
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/etuples/etuples-{{ version }}.tar.gz
  sha256: a474e586683d8ba8d842ba29305005ceed1c08371a4b4b0e0e232527137e5ea3
  patches:

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - cons
    - multipledispatch

test:
  requires:
    - python {{ python_min }}
  imports:
    - etuples

about:
  home: https://github.com/pythological/etuples
  license: Apache-2.0
  summary: Python S-expression emulation using tuple-like objects.
  license_file: LICENSE
  dev_url: https://github.com/pythological/etuples

extra:
  recipe-maintainers:
    - brandonwillard
