{% set name = "etuples" %}
{% set version = "0.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/etuples-{{ version }}.tar.gz
  sha256: 26fde81d7e822837146231bfce4d6ba67eab5d7ed55bc58ba7437c2568051167

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=80.0.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - cons
    - multipledispatch

test:
  imports:
    - etuples
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/pythological/etuples
  dev_url: https://github.com/pythological/etuples
  summary: Python S-expression emulation using tuple-like objects.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - brandonwillard
